### PR TITLE
Feature/registration routes&model

### PR DESCRIPTION
**Pull request by maxkajiwara**
Built basic registration and login features for the backend.
I gave up on figuring out auth0 integration for now. Might try again in the future.

Tested with postman

### CODE REVIEW

**Comment by maxkajiwara** [comment]
[User routes](https://trello.com/c/osxIoKBs/4-user-routes)

**Comment by maxkajiwara** [comment]
[User models](https://trello.com/c/5xMkHgQv/3-user-models)

**Review by fellanonymous — CHANGES_REQUESTED** [review]
Looks fine. Didn't test, but read through the code. Need testing instructions.

**Review by fellanonymous — CHANGES_REQUESTED** [review]
Looks fine. Didn't test, but read through the code. Need testing instructions.

**Review by fellanonymous — CHANGES_REQUESTED** [review]
Looks fine. Didn't test, but read through the code. Need testing instructions.

**Review by fellanonymous — APPROVED** [review]
Looks fine. Didn't test, but read through the code. Need testing instructions.

**Review by fellanonymous — APPROVED** [review]
Looks fine. Didn't test, but read through the code. Need testing instructions.

**Review by fellanonymous — APPROVED** [review]
Looks fine. Didn't test, but read through the code. Need testing instructions.

**Review by fellanonymous — APPROVED** [review]
Looks good. Trying to approve again since GitHub was not allowing me previously. We might want to include test instructions on future pull requests.

**Comment by fellanonymous** [comment]
This is broken.

**Pull request closed without merging**
